<?php
	// $mainInstanceCategories = $v->getData('magento', 'categories'); 
	// array_shift($mainInstanceCategories);
	// // die(var_dump($mainInstanceCategories));
	// $clients = $v->getData('client', 'client');
	// $clientsIds = [];

	// if (isset($_GET['clear_session'])) {
	// 	unset($_SESSION['category_items_count']);
	// }
?>
<div class="content-wrapper">
	<section class="content">
		<div class="row">
			<section class="col-lg-12 connectedSortable">
				<div class="box box-primary">
		            <div class="box-body pad table-responsive">
						<div class="col-md-3 col-sm-6 col-xs-12">
							<div class="info-box <?php// echo $icons['categories'][0] ?>">
								<span class="info-box-icon"><i class="<?php// echo $icons['categories'][1] ?>"></i></span>

								<div class="info-box-content">
									<span class="info-box-text">Categories</span>
									<span class="info-box-number"><?php// echo $items['categories']; ?></span>
									<span class="progress-description">
										Last Sync: <?php// echo $times['categories']; ?>
									</span>
								</div>
	                        </div>
						</div>
					</div>

					<div class="box-body">
						<div class="row">
							<div class="col-md-6">
								<button class="btn btn-primary" id="categories-sync">
									<i class="fa fa-repeat"></i> 
									<label class="btn-label" id="sync-label">Run Synchronization</label>
								</button>
							</div>
						</div>
			        </div>

				</div>

				<div class="col-md-12" id="categories-result-display">
					<div class="box box-solid">
						<div class="box-header with-border">
							<i class="fa fa-user"></i><h3 class="box-title">Categories Log Activity</h3>
						</div>
						<div class="box-body">
							<div class="progress active" style="margin-bottom: 0;">
								<div class="progress-bar progress-bar-primary progress-bar-striped progress-bar-animated six-sec-ease-in-out" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" data-transitiongoal-backup="100">
									<p id="completed"></p>
								</div>
							</div>
						</div>
						<div class="box-body" id="categories-result"></div>
					</div>
				</div>
			</section>
		</div>
	</section>
</div>

<script>
	// $(document).ready(function($) {
	// 	$('#categories-sync').on('click', function(event) {
	// 		$('#client-notifier').removeClass('hidden');

	// 		$('#categories-result').empty();

	// 		var client = '';
	// 		if ($('#client-select').is(':disabled')) {
	// 			client = <?php// // echo json_encode($clientsIds); ?>;
	// 		}else{
	// 			client = $('#client-select').val();
	// 		}
	// 		// $('#client-notifier').children('b#cn').html('Adding data for ');
	// 		toastr.options = {
	// 			"closeButton": true,
	// 			"positionClass": "toast-top-center"
	// 		};

	// 		if (client.length == 0) {
	// 			toastr.error('Please choose one or more clients!!!');
	// 		}else{
	// 			$('.fa-repeat').addClass('fa-spin');
	// 			$('#categories-sync').addClass('disabled');
	// 			$('#sync-label').html('Running Synchronization...');

	// 			var data = <?php// echo json_encode($mainInstanceCategories); ?>;
	// 			let i = 0;
	// 			let ccounter = 0;

	// 			var tmpArr1 = data;
	// 			var totalData = data;

	// 			for (var j = 0; j < client.length - 1; j++) {
	// 				totalData = totalData.concat(tmpArr1);
	// 			}

	// 			insertAsync(totalData, i, client, ccounter, 'categories');
	// 		}
	// 	});
	// });
</script>