<?php // 
	// if (isset($_GET['clear_session'])) {
	// 	unset($_SESSION['items_count']);
	// }
?>

<div class="content-wrapper">
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<section class="col-lg-12 connectedSortable">
				<div class="box box-primary">
		            <div class="box-header">
		              <i class="fa fa-edit"></i>
		              <h3 class="box-title">Products</h3>
		            </div>
		            <div class="box-body pad table-responsive">
						<div class="col-md-3 col-sm-6 col-xs-12">
							<div class="info-box <?php // echo $icons['products'][0] ?>">
								<span class="info-box-icon"><i class="<?php // echo $icons['products'][1] ?>"></i></span>

								<div class="info-box-content">
									<span class="info-box-text">Products</span>
									<span class="info-box-number"><?php // echo $items['products']; ?></span>
									<span class="progress-description">
										Last Sync: <?php // echo $times['products']; ?>
									</span>
								</div>
	                        </div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12" id="products-result-display">
						<div class="box box-solid">
							<div class="box-header with-border">
								<i class="fa fa-user"></i><h3 class="box-title">Products Log Activity</h3>
							</div>
							<div class="box-body">
								<div class="progress active" style="margin-bottom: 0;">
									<div class="progress-bar progress-bar-primary progress-bar-striped progress-bar-animated six-sec-ease-in-out" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" data-transitiongoal-backup="100">
										<p id="completed"></p>
									</div>
								</div>
							</div>
							<div class="box-body" id="products-result"></div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</section>
</div>

<script>
	// $(document).ready(function($) {

	//     $('.select2lang').select2();
	//     $('.select2warehouse').select2();

	// 	$('#products-sync').on('click', function(event) {
	// 		var lang = $('#langselect').val();
	// 		var warehouse = $('#warehouseselect').val();

	// 		toastr.options = {
	// 			"closeButton": true,
	// 			"positionClass": "toast-top-center"
	// 		};

	// 		if (lang.length == 0 || warehouse.length == 0) {
	// 			toastr.error('Please choose languages to use and warehouse!!!');
	// 		}else{
	// 			var loader = '<img src="views/img/loader.gif" style="width: 40px;">';
	// 			// getProducts with ajax request and with a foreach loop add them in magento
	// 			var data = '';
	// 			$.ajax({
	// 				url: 'getproducts.php',
	// 				type: 'POST',
	// 				data: {langs: lang, warehouse: warehouse},
	// 				beforeSend: function () {
	// 					$('.fa-repeat').addClass('fa-spin');
	// 					$('#products-sync').addClass('disabled');
	// 					$('#sync-label').html('Running Synchronization...');
	// 					$('#products-result').append('<p id=\'transaction\' style="font-size: 20px;font-weight: bold;">Fetching products from Odoo ' + loader +'</p>');
	// 				},
	// 				success: function (result) {
	// 					if (result) {
	// 						data = JSON.parse(result);
	// 						let i = 0;
	// 						if (data.length > 0) {
	// 							$('#products-result').html('<h4 style="font-size: 20px;font-weight: bold;">Products loaded from ERP! Pushing products in Magento...</h4>');
	// 							syncAsync(data, i, 'products');
	// 						}else{
	// 							Swal.fire({
	// 								type: 'error',
	// 								title: 'Error...',
	// 								text: 'There are no products to sync!',
	// 							}).then((result) => {
	// 								$('#products-result').html('');
	// 								$('.fa-repeat').removeClass('fa-spin');
	// 								$('#products-sync').removeClass('disabled');
	// 								$('#sync-label').html('Run Synchronization');
	// 							});
	// 						}
	// 					}
	// 				}
	// 			});
	// 		}
	// 	});
	// });
</script>
